version: "2"
linters:
  enable:
    - dupl
    - gocyclo
    - revive
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: var-naming
        - name: indent-error-flow
        - name: empty-block
        - name: unused-parameter
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
