run:
	GIN_MODE=release go run app.go
	# tail -f /dev/null

install:
	GIN_MODE=release go get -u github.com/gin-gonic/gin gorm.io/gorm gorm.io/driver/postgres github.com/dgrijalva/jwt-go github.com/minio/minio-go/v7
