// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppendMessage(ctx context.Context, arg AppendMessageParams) (ChatsMessages, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (ChatsSessions, error)
	// Needed to check that the message exists before setting a like/dislike
	GetMessageByID(ctx context.Context, id pgtype.UUID) (ChatsMessages, error)
	// Needed to validate user permissions in the service before any action
	GetSessionByID(ctx context.Context, id pgtype.UUID) (ChatsSessions, error)
	GetSessionMessages(ctx context.Context, sessionID pgtype.UUID) ([]ChatsMessages, error)
	GetUserSessions(ctx context.Context, userID pgtype.UUID) ([]ChatsSessions, error)
	// We use ON CONFLICT since there's a UNIQUE index on message_id.
	// If the user changes their mind and clicks 'dislike' instead of 'like', the row gets updated.
	SetFeedback(ctx context.Context, arg SetFeedbackParams) (ChatsFeedback, error)
	// Instead of a physical delete, we set a timestamp
	SoftDeleteSession(ctx context.Context, id pgtype.UUID) error
	UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error
}

var _ Querier = (*Queries)(nil)
