// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUsers, error)
	GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (GetUserByIdRow, error)
	IsLoginAvailable(ctx context.Context, login *string) (bool, error)
	UpdateUserToRegistered(ctx context.Context, arg UpdateUserToRegisteredParams) (AuthUsers, error)
}

var _ Querier = (*Queries)(nil)
