// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/0hJonny/langfuse-agents/internal/auth/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (email, password_hash, role, name, login)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, role, created_at, updated_at, name, login
`

type CreateUserParams struct {
	Email        *string         `json:"email"`
	PasswordHash *string         `json:"password_hash"`
	Role         domain.UserRole `json:"role"`
	Name         *string         `json:"name"`
	Login        *string         `json:"login"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUsers, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role, arg.Name, arg.Login)
	var i AuthUsers
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Login,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT a.id,
       a.email,
       a.password_hash,
       a.created_at,
       a.role,
       a.name,
       a.login
  FROM auth.users a
WHERE a.email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        *string            `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Role         domain.UserRole    `json:"role"`
	Name         *string            `json:"name"`
	Login        *string            `json:"login"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.Name,
		&i.Login,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT a.id,
       a.email,
       a.password_hash,
       a.created_at,
       a.role,
       a.name,
       a.login
  FROM auth.users a
WHERE a.id = $1
LIMIT 1
`

type GetUserByIdRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        *string            `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Role         domain.UserRole    `json:"role"`
	Name         *string            `json:"name"`
	Login        *string            `json:"login"`
}

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Role,
		&i.Name,
		&i.Login,
	)
	return i, err
}

const updateUserToRegistered = `-- name: UpdateUserToRegistered :one
UPDATE auth.users
   SET email = $1,
       password_hash = $2,
       name = $3,
       login = $4,
       role = 'user',
       updated_at = CURRENT_TIMESTAMP
 WHERE id = $5
RETURNING id, email, password_hash, role, created_at, updated_at, name, login
`

type UpdateUserToRegisteredParams struct {
	Email        *string     `json:"email"`
	PasswordHash *string     `json:"password_hash"`
	Name         *string     `json:"name"`
	Login        *string     `json:"login"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserToRegistered(ctx context.Context, arg UpdateUserToRegisteredParams) (AuthUsers, error) {
	row := q.db.QueryRow(ctx, updateUserToRegistered, arg.Email, arg.PasswordHash, arg.Name, arg.Login, arg.ID)
	var i AuthUsers
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Login,
	)
	return i, err
}

const isLoginAvailable = `-- name: IsLoginAvailable :one
SELECT NOT EXISTS (SELECT 1 FROM auth.users WHERE login = $1) AS available
`

func (q *Queries) IsLoginAvailable(ctx context.Context, login *string) (bool, error) {
	row := q.db.QueryRow(ctx, isLoginAvailable, login)
	var available bool
	err := row.Scan(&available)
	return available, err
}
