export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_NOT_FOUND: 'AUTH_ACCOUNT_NOT_FOUND',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
  EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  INVALID_EMAIL: 'AUTH_INVALID_EMAIL',
  LOGIN_TAKEN: 'AUTH_LOGIN_TAKEN',
  INVALID_LOGIN: 'AUTH_INVALID_LOGIN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  NETWORK_ERROR: 'NETWORK_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
  UNKNOWN: 'UNKNOWN',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

export function isErrorCode(code: string): code is ErrorCode {
  return (Object.values(ERROR_CODES) as string[]).includes(code)
}
